apiVersion: sagemaker.amazonaws.com/v1
kind: HyperPodPyTorchJob
metadata:
  labels:
    app.kubernetes.io/name: HyperPod
    app.kubernetes.io/managed-by: kustomize
    app: TRAINING_JOB_NAME
  name: TRAINING_JOB_NAME
spec:
  nprocPerNode: "NPROC_PER_NODE"
  replicaSpecs:
    - name: pods
      replicas: REPLICAS_COUNT
      template:
        spec:
          serviceAccountName: mlflow-service-account
          # serviceAccountName: hp-training-operator-pod-manager
          nodeSelector:
            beta.kubernetes.io/instance-type: INSTANCE_TYPE
          containers:
            - name: pytorch
              image: DOCKER_IMAGE
              imagePullPolicy: Always
              ports:
                - containerPort: 8080 # HyperPodElasticAgent port
              resources:
                requests:
                  nvidia.com/gpu: NPROC_PER_NODE
                  vpc.amazonaws.com/efa: EFA_PER_NODE
                limits:
                  nvidia.com/gpu: NPROC_PER_NODE
                  vpc.amazonaws.com/efa: EFA_PER_NODE
              env:
              - name: LOGLEVEL
                value: "INFO"
              - name: FI_PROVIDER
                value: "efa"
              # - name: TORCH_DISTRIBUTED_DEBUG
              #   value: "DETAIL"
              # - name: TORCH_NCCL_ENABLE_MONITORING
              #   value: "1"
              # - name: TORCH_NCCL_TRACE_BUFFER_SIZE
              #   value: "20000"
              - name: NCCL_DEBUG
                value: "DEBUG"
              # - name: NCCL_SOCKET_IFNAME
              #   value: "^lo"
              - name: NCCL_SOCKET_IFNAME
                value: "eth0"
              # - name: TORCH_NCCL_ASYNC_ERROR_HANDLING
              #   value: "1"
              # - name: HF_TOKEN
              #   value: "12345"
              - name: MLFLOW_TRACKING_URI
                value: SM_MLFLOW_ARN
              - name: MLFLOW_EXPERIMENT_NAME
                value: TRAINING_JOB_NAME
              - name: MLFLOW_TAG_NPROCPERNODE
                value: "NPROC_PER_NODE"
              - name: MLFLOW_TAG_REPLICAS
                value: "REPLICAS_COUNT"
              - name: MLFLOW_TAG_EFAPERNODE
                value: "EFA_PER_NODE"
              - name: MLFLOW_TAG_INSTANCETYPE
                value: INSTANCE_TYPE
              command: ["bash", "ENTRY_SCRIPT_PATH"]
              volumeMounts:
                - name: persistent-storage-s3
                  mountPath: /s3
                  readOnly: false
                - name: shmem
                  mountPath: /dev/shm
                - name: local
                  mountPath: /local
                - name: inst-nvme
                  mountPath: /ckpt-path
                - name: local-cache
                  mountPath: /root/.cache
                # - name: persistent-storage
                #   mountPath: /dfsx
          volumes:
            - name: shmem
              hostPath: 
                path: /dev/shm
            - name: local
              hostPath:
                path: /mnt/k8s-disks/0
            - name: local-cache
              hostPath:
                path: /opt/dlami/nvme/.cache
            - name: inst-nvme
              hostPath:
                path: /opt/dlami/nvme/
            # - name: persistent-storage
            #   persistentVolumeClaim:
            #     claimName: fsx-claim
            - name: persistent-storage-s3
              persistentVolumeClaim:
                claimName: s3-claim
  runPolicy:
    jobMaxRetryCount: 5
    restartPolicy:
      numRestartBeforeFullJobRestart: 3
      evalPeriodSeconds: 21600
      maxFullJobRestarts: 1
    cleanPodPolicy: "All"LOG_MONITORING_CONFIG
