---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-MODEL_TAG-inference
  labels:
    app: vllm-MODEL_TAG-inference
    model-type: "vllm"
    model-id: "ENCODED_MODEL_ID"
    model-tag: "MODEL_TAG"
spec:
  replicas: REPLICAS_COUNT
  selector:
    matchLabels:
      app: vllm-MODEL_TAG-inference
  template:
    metadata:
      labels:
        app: vllm-MODEL_TAG-inference
    spec:
      containers:
        - name: vllm-openai
          image: DOCKER_IMAGE
          resources:
            limits:
              nvidia.com/gpu: GPU_COUNT
            requests:
              cpu: "4"
              memory: 8Gi
              nvidia.com/gpu: GPU_COUNT
          command: VLLM_COMMAND
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: persistent-storage-s3
              mountPath: /s3
              readOnly: true
            - name: local-cache
              mountPath: /root/.cache
            - name: shm
              mountPath: /dev/shm
          env:HF_TOKEN_ENV
            - name: TRANSFORMERS_CACHE
              value: "/root/.cache/huggingface"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      volumes:
        - name: persistent-storage-s3
          persistentVolumeClaim:
            claimName: s3-claim
        - name: local-cache
          hostPath:
            path: /opt/dlami/nvme/.cache
            type: DirectoryOrCreate
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-MODEL_TAG-nlb
  annotations:NLB_ANNOTATIONS
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
  selector:
    app: vllm-MODEL_TAG-inference
  type: LoadBalancer
