task: gsm8k
projectDir: /fsx/rl-agentic-on-aws
modelPath: /fsx/models/Qwen3-0.6B

data:
  train: /fsx/data/gsm8k/train.parquet
  validation: /fsx/data/gsm8k/test.parquet

tool:
  config: /workspace/verl/verl/examples/sglang_multiturn/config/tool_config/gsm8k_tool_config.yaml

verl:
  projectName: agentic-rl-tooluse
  batchSize: 8
  rolloutN: 4
  epochs: 1
  quick: false
  trainGpus: 4
  rolloutGpus: 4
  promptLength: 1024
  responseLength: 1024
